version: '2'
services:
    php:
        build: ./.docker/testing
        volumes:
          - .:/var/www/html
        restart: always
        ports:
          - 8888:80
    # Test database
    test_db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
          - 3366:3306
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: phuby